project:
  name: quickstart-dotnetfx-ecs-cicd
  regions:
  - eu-west-1
  package_lambda: false
tests:
  default:
    template: ./templates/quickstart-dotnetfx-ecs-cicd-new-cluster.template.yaml
    parameters:
      EcsClusterName: "taskcat"
      EcsServiceName: "taskcat-service"
      TaskContainerName: "sampleapp"
      GitHubRepositoryName: "quickstart-dotnetfx-ecs-cicd"
      GitHubBranchName: "develop"
      GitHubOwner: override
      GitHubOAuthToken: override
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
